/**
 * University Data Service
 * Сервис по работе с университетскими данными
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.accountdataservice.university_data_client.api

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.request.*
import io.ktor.http.*
import org.astu.accountdataservice.university_data_client.model.AddStudentGroupRequest
import org.astu.accountdataservice.university_data_client.model.StudentGroupDto

class StudentGroupControllerApi(
    private val httpClient: HttpClient,
    private val basePath: String = "http://localhost:8080"
) {

    /**
     *
     *
     * @param body
     * @return StudentGroupDto
     */
    suspend fun addStudentGroup(body: AddStudentGroupRequest): StudentGroupDto {
        val response = httpClient.post("${basePath}api/student-groups") {
            setBody(body)
        }
        return when (response.status) {
            HttpStatusCode.OK -> response.body<StudentGroupDto>()
            else -> throw IllegalStateException("${response.status}")
        }
    }

    /**
     *
     *
     * @return kotlin.Array<StudentGroupDto>
     */
    suspend fun getAllStudentGroups(): List<StudentGroupDto> {
        val response = httpClient.get("${basePath}api/student-groups")
        return when (response.status) {
            HttpStatusCode.OK -> response.body<List<StudentGroupDto>>()
            else -> throw IllegalStateException("${response.status}")
        }
    }
}
