spring:
  application:
    name: AccountDataService
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435}/${DATABASE_NAME:accountDataDb}?currentSchema=${DATABASE_SCHEMA:public}
    username: ${SPRING_DATASOURCE_USERNAME:azimusma}
    password: ${SPRING_DATASOURCE_PASSWORD:azimusma}
    driver-class-name: org.postgresql.Driver
server:
  tomcat:
    threads:
      max: 4
service:
  url: ${UNI_SERVICE_URL:http://localhost:8080}
