spring:
  application:
    name: AccountDataService
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432}/${DATABASE_NAME:account_data_db}?currentSchema=${DATABASE_SCHEMA:public}
    username: ${SPRING_DATASOURCE_USERNAME:azimusma}
    password: ${SPRING_DATASOURCE_PASSWORD:azimusma}
    driver-class-name: org.postgresql.Driver
