/**
 * University Data Service
 * Сервис по работе с университетскими данными
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.astu.accountdataservice.university_data_client.model

import kotlinx.serialization.Serializable


/**
 * 
 * @param name 
 * @param description 
 */
@Serializable
data class AddDepartmentRequest (

    val name: String,
    val description: String
)